default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["BIRCH_HILL_API_DATABASE_HOST"] %>
  port: <%= ENV["BIRCH_HILL_API_DATABASE_PORT"] %>
  username: <%= ENV["BIRCH_HILL_API_DATABASE_USERNAME"] %>
  password: <%= ENV["BIRCH_HILL_API_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: birch_hill_api_development

test:
  <<: *default
  database: birch_hill_api_test

production:
  <<: *default
  database: birch_hill_api_production
  username: birch_hill_api
  password: <%= ENV["BIRCH_HILL_API_DATABASE_PASSWORD"] %>
